print("The story of Maynesborough, by Big Sparky. Licensed under the SparkyConditionless license; see the file named \"license\" for details. Press enter to continue.")
input()
print("In the town of Maynesborough, in the county of Maynes, in a country not too dissimilar to the United Kingdom, lived Teiya, a young girl, who had just met Alfo, a young man.")
print("Teiya came home from work after she got a message that her mother had travelled to Mayscore, with her stating to Alfo, \"Ah, Alfo, me old mum had just travelled to Mayscore, and she's havin\' a rootin\' time, I bet ya!\"")
print("(Press enter to continue)")
input()
print("\"Mayscore, eh?\" Alfo replied. \"Well, my mother is out of town, too!\" Jakka heard the conversation and chimed in, \"Mayscore, huh? I hear there was a fair going on. I didn't come because I had other plans, like walking my sons and daughters to school and trading on the Mayscore Stocks.\"")
print("\"Mayscore Stocks, right? I hear that LunaBank closed down recently. What a shame.\" said Alfo. \"Aw, darn! Now everyone will 'afta change to another bank!\" exclaimed Teiya.")
print("(Press enter to continue)")
input()
print("\"Huh... Well, let's move to Naybridge-\" said Alfo; Teiya interrupted \"because I hear there's a competition!\" Alfo and Teiya travelled to Naybridge Markpoint, while Jakka travelled to Mayscore Markpoint, in order to attend a Markpoint Meeting, which occurs once a day.")
print("\"The Markpoints are located in the centre of the community and the towns and cities are built around the Markpoints,\" the country guide readers stated, \"and they were built long ago in specific spots; these were so that the monarchs and their mappers would easily map the entire land out, and that regions could be marked and data easily gathered. In order to build a new settlement, and therefore a new Markpoint, people have to get permission from the Government.\"")
print("(Press enter to continue)")
input()
print("The country guides were recited once a day in the respective Markpoint Halls - the Markpoint Meetings had a script devised by the old, and everyone had to attend at least one Markpoint Meeting, located in the Markpoint Halls, per year, otherwise they would be fined the equivalent to the price of two weeks' pay.")
print("The fine would be waived if the age of the person was 17 or younger, as the government stated \"No minor shall be required to attend these meetings, for they are largely only applicable to adults.\"")
print("(Press enter to continue)")
input()
