print("The story of Maynesborough, by Big Sparky. Licensed under the SparkyConditionless license; see the file named \"license\" for details.")
input("(Press enter to continue)")
print("In the town of Maynesborough, in the county of Maynes, in a country not too dissimilar to the United Kingdom, lived Teiya, a young girl, who had just met Alfo, a young man.")
print("Teiya came home from work after she got a message that her mother had travelled to Mayscore, with her stating to Alfo, \"Ah, Alfo, me old mum had just travelled to Mayscore, and she's havin\' a rootin\' time, I bet ya!\"")
input("(Press enter to continue)")
print("\"Mayscore, eh?\" Alfo replied. \"Well, my mother is out of town, too!\" Jakka heard the conversation and chimed in, \"Mayscore, huh? I hear there was a fair going on. I didn't come because I had other plans, like walking my sons and daughters to school and trading on the Mayscore Stocks.\"")
print("\"Mayscore Stocks, right? I hear that LunaBank closed down recently. What a shame.\" said Alfo. \"Aw, darn! Now everyone will 'afta change to another bank!\" exclaimed Teiya.")
input("(Press enter to continue)")
print("\"Huh... Well, let's move to Naybridge-\" said Alfo; Teiya interrupted \"because I hear there's a competition!\" Alfo and Teiya travelled to Naybridge Markpoint, while Jakka travelled to Mayscore Markpoint, in order to attend a Markpoint Meeting, which occurs once a day.")
print("\"The Markpoints are located in the centre of the community and the towns and cities are built around the Markpoints,\" the country guide readers stated, \"and they were built long ago in specific spots; these were so that the monarchs and their mappers would easily map the entire land out, and that regions could be marked and data easily gathered. In order to build a new settlement, and therefore a new Markpoint, people have to get permission from the Government.\"")
input("(Press enter to continue)")
print("The country guides were recited once a day in the respective Markpoint Halls - the Markpoint Meetings had a script devised by the old, and everyone had to attend at least one Markpoint Meeting, located in the Markpoint Halls, per year, otherwise they would be fined the equivalent to the price of two weeks' pay.")
print("The fine would be waived if the age of the person was 17 or younger, as the government stated \"No minor shall be required to attend these meetings, for they are largely only applicable to adults.\"")
input("(Press enter to continue)")
print("\"These meetings are fun, but why every day?\" asked Alfo. \"Government says so. We also get paid lots for this, especially on day one of the Final Week of the Year. We get paid thrice the amount we normally get on that day, and we don't get taxed for any bonuses we receive. You should do one of these one time, young one.\"")
print("\"I see... In any case, I gotta get back to Jakka, one of my fellows; Teiya came with me, because she wants to take part in this \"competition nonsense\".\" said Alfo.")
input("(Press enter to continue)")
print("Teiya and Alfo then rushed to get Jakka, then the trio rushed to Naybridge Fair. Teiya purchased a Trio Ticket, and she took part in a strength test competition. She came first place, but got scorned at by the others.")
print("\"Hey! What did I do?\" questioned Teiya, as she wanted an escape. The situation calmed down; The others apologised as soon as she questioned them. \"We\'re sorry, ma\'am. You did well.\" one said, as another hugged her with her consent.")
input("(Press enter to continue)")
print("Alfo and Jakka then left for Mayscore Mall, while Teiya went home. Alfo went to a playplace in the mall whie Jakka drifted around until he saw the food market; he bought bread and cream, as he loved bread in sweetened cream.")
print("Teiya wrote a letter to Saterl, her best friend. She wrote \"Saterl, when do you want to meet up?\" and sighed, thinking all about those allegations against Olan, a local celebrity. Olan wanted to protest against the government\'s policies on work, but he was dealing with allegations that he got in trouble with Alfo, as Olan was indebted towards Alfo.")
input("(Press enter to continue)")
print("In another part of Maynesborough, Alfo's and Olan's parents agreed to settle the debt; Olan's and Alfo's respective parents had written a letter for the both to read together.")
print("They came back home later, and started to worry about how to fix each other's relationships. \"How do we tell them?\" asked Olan. \"I dunno.\" said Alfo. \"Maybe we should ask Teiya.\" said Olan.")
input("(Press enter to continue)")
print("\"Teiya!\" both yelled. \"What now, you 2? Olan, I thought ya-\" said Teiya, greeting both at the door. \"It's OK! Our parents did the debt thing and told us, through a letter, that they give I-owe-yous to each other on a regular basis and not to worry about anything.\"")
print("\"I see... I dunno how yer reputation's going to be fixed, Olan!")
#I'm taking a break from writing.